In [58]:
# Q.1 Create a dataset as follow in the table.
import pandas as pd
data={'Tid':list(range(1,11)),
      'Refund':["Yes","No","No","Yes","No","No","Yes","No","No","No"],
      'Marital Status':["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
      'Taxable Income':[125000,100000,70000,120000,95000,60000,220000,85000,75000,90000],
      'Cheat':["No","No","No","No","Yes","No","No","Yes","No","Yes"]}

df=pd.DataFrame(data)
df

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single          125000    No
1    2     No        Married          100000    No
2    3     No         Single           70000    No
3    4    Yes        Married          120000    No
4    5     No       Divorced           95000   Yes
5    6     No        Married           60000    No
6    7    Yes       Divorced          220000    No
7    8     No         Single           85000   Yes
8    9     No        Married           75000    No
9   10     No         Single           90000   Yes

In [59]:
# Q.2 From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.
print("Row 0 \n",df.loc[0])
print("\nRow 4 \n",df.loc[4])
print("\nRow 7\n",df.loc[7])
print("\nRow 8\n",df.loc[8])

Row 0
 Tid                    1
Refund               Yes
Marital Status    Single
Taxable Income    125000
Cheat                 No
Name: 0, dtype: object

Row 4
 Tid                      5
Refund                  No
Marital Status    Divorced
Taxable Income       95000
Cheat                  Yes
Name: 4, dtype: object

Row 7
 Tid                    8
Refund                No
Marital Status    Single
Taxable Income     85000
Cheat                Yes
Name: 7, dtype: object

Row 8
 Tid                     9
Refund                 No
Marital Status    Married
Taxable Income      75000
Cheat                  No
Name: 8, dtype: object

In [60]:
# Q.3 Navigate the DataFrame and do the following task for the table created in question 1:
# 1. Select row from index 3 to 7.
df.iloc[3:8]

   Tid Refund Marital Status  Taxable Income Cheat
3    4    Yes        Married          120000    No
4    5     No       Divorced           95000   Yes
5    6     No        Married           60000    No
6    7    Yes       Divorced          220000    No
7    8     No         Single           85000   Yes

In [61]:
# 2. Select row from index 4 to 8, and column 2 to 4.
df.iloc[4:9,2:5]

  Marital Status  Taxable Income Cheat
4       Divorced           95000   Yes
5        Married           60000    No
6       Divorced          220000    No
7         Single           85000   Yes
8        Married           75000    No

In [62]:
# 3. Select all rows with column index 1 to 3 (include index 3 during selection).
df.iloc[:,1:4]

  Refund Marital Status  Taxable Income
0    Yes         Single          125000
1     No        Married          100000
2     No         Single           70000
3    Yes        Married          120000
4     No       Divorced           95000
5     No        Married           60000
6    Yes       Divorced          220000
7     No         Single           85000
8     No        Married           75000
9     No         Single           90000

In [63]:
# Q.4 Read a csv file and display its first five rows.
df_csv=pd.read_csv('Iris.csv')
df_csv.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [64]:
# Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the
# result.
df_drop=df_csv.copy()
df_drop.drop(4,axis=0,inplace=True)
df_drop.drop(columns="PetalLengthCm",inplace=True)
df_drop

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [65]:
# Q.6 Create a sample dataset (employees.csv) containing information about employees in
# a company.
df_emp=pd.read_csv("/content/employees.csv")
df_emp

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [66]:
# a) Shape (number of rows and columns) of the DataFrame.
print(df_emp.shape)

(5, 10)

In [67]:
# b) Summary of the DataFrame that includes the data types and non-null counts for
# each column.
print(df_emp.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes
None

In [68]:
# c) Generate descriptive statistics.
df_emp.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [69]:
# d) Display the first 5 rows  of the dataset.
df_emp.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [70]:
# d) Display the last 3 rows of the dataset.
df_emp.tail(n=3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [71]:
# e) Calculate the following statistics from the dataset:
# i. The average salary of employees.
print(df_emp['Salary'].mean())

60000.0

In [72]:
# ii. The total bonus paid to all employees.
print(df_emp['Bonus'].sum())

27500

In [73]:
# iii. The youngest employee's age.
print(df_emp['Age'].min())

28

In [74]:
# iv. The highest performance rating.
print(df_emp['Rating'].max())

4.7

In [75]:
# f) Sort the DataFrame by the Salary column in descending order.
df_emp.sort_values(["Salary"],ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [76]:
def cat(r):
  if r['Rating']>=4.5:
    return "Excelent"
  elif r['Rating']>=4:
    return "Good"
  else :
    return "Average"
df_emp["Category"]=df_emp.apply(cat,axis=1)
df_emp

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excelent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excelent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [77]:
# h) Identify missing values in the DataFrame.
print(df_emp.isnull().sum())

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Category               0
dtype: int64

In [78]:
# i) Rename the Employee_ID column to ID.
df_emp=df_emp.rename(columns={'Employee_ID':'Id'})
df_emp

,Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excelent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excelent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [79]:
# j) Find all employees who:
# i. Have more than 5 years of experience.
df_exp=df_emp[df_emp['Years_of_Experience']>5]
df_exp

,Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [80]:
# ii. Belong to the IT department.
df_it=df_emp[df_emp['Department']=='IT']
df_it

,Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [81]:
# k) Modify the dataset by adding a new column, Tax, which deducts 10% of the
# Salary.
df_emp['Tax']=df_emp['Salary']*0.10
df_emp

,Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excelent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excelent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [82]:
# l) Save the modified DataFrame (with added columns) to a new CSV file.
df_emp.to_csv("new employee data.csv",index=False)